{% set version = "1.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-parallelmap
  version: {{ version|replace("-", "_") }}

source:
  fn: parallelMap_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/parallelMap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/parallelMap/parallelMap_{{ version }}.tar.gz
  sha256: fb6f15e325f729f1c5218768b17c20909ee857069c6cc5d8df50e1dafe26ed5b

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bbmisc >=1.8
    - r-checkmate >=1.5.1
  run:
    - r-base
    - r-bbmisc >=1.8
    - r-checkmate >=1.5.1

test:
  commands:
    - $R -e "library('parallelMap')"           # [not win]
    - "\"%R%\" -e \"library('parallelMap')\""  # [win]

about:
  home: https://github.com/berndbischl/parallelMap
  license: BSD_2_clause
  summary: Unified parallelization framework for multiple back-end, designed for internal package
    and interactive usage. The main operation is a parallel "map" over lists. Supports
    local, multicore, mpi and BatchJobs mode. Allows "tagging" of the parallel operation
    with a level name that can be later selected by the user to switch on parallel execution
    for exactly this operation.
  license_family: BSD

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
