travis:
  secure:
    BINSTAR_TOKEN: UAE6rCD8WTGZBjK5zFiZ27HX+rIO1E6n/W4OGvZGffIhfjVDe+2T7cJ0oHcgjP+K06no0iYko8RXF0E7MvygRMrB8gcbufxwO7vFv3EhDrmg7SAPUYtc/c8L4pdZAVSetRSkrel1Raf+Jua3saJdPoHFSxIgaS7w1P/A5GRq2qtu3MaeIGoZIC634t3GsaoR+H9DHzjxDp6ijsuFchaABHBrITWfKg+PaamR70ZB4TpVb1mo7oeqJluF+UQGHfehv3IQRtJEA+L04AHc3jN8zYrpDEqo/lk+rUiNzIVkt8VRpdHP2A884/t5jFszS/t2WXN+Gd1dPUh3pEk6mE+szxaXpAbEu+AVuYsxX6hPfa8w55PxNO8/0fzDbXBGY3wFFwhF3ASn8PJUXEU/Ym0XeqwHX5wnnzArCQNjxP7IuJo03B3w7IfpjMOzNwzVFZaQBUJdvJdLPCsCel1gFdKGlziaUleyjZNNu330Nd9pfRaQMvuDmc0KTBfnQRouaXAQZ0QK51JZPvyaJWqCbKHyOPXcNCjpWDxuVa2af3RysSgkjJ2uMQHrVPiq8K73Eekr1ueMk/unMLQtcGOlXreZZ9fRT4u6lgbjFPngnH7YPnDzC89tV/zaZofZE+ygzdQ/ymhkUDE1hIxfOshf/QYnVyEIl+QVjU6voPHW/4wGPpg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
